In [11]:
import pandas as pd

In [12]:
ca_fire_df = pd.read_csv('output_data/california_fire_cleaned.csv')
ca_fire_df.head()

,Counties,AcresBurned,AirTankers,ArchiveYear,Name,CountyIds,CrewsInvolved,Dozers,Engines,Extinguished,...,PersonnelInvolved,Started,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,WaterTenders,Started Month,Days Burned
0,Imperial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,San Diego,7055.0,NaN,2013.0,San Diego,37,56.0,24.0,183.0,2013-07-15T06:15:00Z,...,2147.0,2013-07-06T12:55:00Z,9.0,149.0,NaN,NaN,ee19b2ec-a96a-4738-994e-fb3ea016e053,24.0,7.0,9.0
2,San Diego,2781.0,25.0,2013.0,San Diego,37,33.0,25.0,73.0,2013-05-26T17:45:00Z,...,911.0,2013-05-23T12:20:00Z,NaN,NaN,NaN,NaN,859479e3-918c-42c6-bb74-5fdc17930a16,26.0,5.0,3.0
3,San Diego,2236.0,NaN,2013.0,San Diego,37,NaN,NaN,NaN,2013-10-09T19:00:00Z,...,NaN,2013-10-05T12:45:00Z,NaN,NaN,NaN,NaN,9fb847ce-44c7-4a11-a733-a6cc82838671,NaN,10.0,4.0
4,San Diego,1271.0,27.0,2013.0,San Diego,37,54.0,27.0,42.0,2013-05-31T06:15:00Z,...,1217.0,2013-05-26T12:04:00Z,NaN,NaN,NaN,NaN,07a5397c-a665-4f84-9a82-5f689cb2c8f3,27.0,5.0,5.0

In [13]:
id_count = ca_fire_df['UniqueId'].value_counts().to_frame().reset_index()
uid_count = id_count.loc[id_count['UniqueId'] > 1]
df_index = []

for i in uid_count['index']:
    index = ca_fire_df[ca_fire_df['UniqueId']==i]
    df_index.append(index)
    for x in index:
#         if x == 
        ca_fire_df.loc[x, ['AcresBurned', 
                           'Dozers',
                           'Engines', 
                           'PersonnelInvolved', 
                           'WaterTenders']] = ca_fire_df.loc[x, ['AcresBurned',
                                                                 'Dozers',
                                                                 'Engines', 
                                                                 'PersonnelInvolved', 
                                                                 'WaterTenders']].div(len(index))

df_index

KeyError: 'Counties'